# Form implementation generated from reading ui file 'untitled_.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import resources
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRectF
from PyQt6.QtGui import QPainter, QColor, QPainterPath
from PyQt6.QtCore import Qt
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 314)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.95, y2:0.16, stop:0 #8EC5FC, stop:1 #E0C3FC);\n"
"    font-family: \"Oswald\", sans-serif;\n"
"    border-radius: 7px;\n"
"}")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.DockOption.AllowTabbedDocks | QtWidgets.QMainWindow.DockOption.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rec_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rec_start.setGeometry(QtCore.QRect(195, 255, 51, 51))
        self.rec_start.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rec_start.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"}\n"
"")
        self.rec_start.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/start.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rec_start.setIcon(icon)
        self.rec_start.setIconSize(QtCore.QSize(47, 47))
        self.rec_start.setCheckable(True)
        self.rec_start.setObjectName("rec_start")
        self.rec_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rec_stop.setGeometry(QtCore.QRect(255, 255, 51, 51))
        self.rec_stop.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rec_stop.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"\n"
"")
        self.rec_stop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/stop.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rec_stop.setIcon(icon1)
        self.rec_stop.setIconSize(QtCore.QSize(50, 50))
        self.rec_stop.setObjectName("rec_stop")
        self.rec_pause = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rec_pause.setGeometry(QtCore.QRect(315, 255, 51, 51))
        self.rec_pause.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rec_pause.setAutoFillBackground(False)
        self.rec_pause.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 155), stop:0.301136 rgba(23, 140, 228, 155), stop:1 rgba(0, 189, 219, 155));\n"
"}\n"
"\n"
"\n"
"")
        self.rec_pause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/pause.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rec_pause.setIcon(icon2)
        self.rec_pause.setIconSize(QtCore.QSize(43, 43))
        self.rec_pause.setObjectName("rec_pause")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 601, 231))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border: none;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(410, 17, 61, 31))
        self.label_5.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(90, 7, 200, 50))
        self.label.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(100, 50, 401, 22))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ClosedHandCursor))
        self.horizontalSlider.setStyleSheet("QSlider:horizontal {\n"
"    background-color: rgba(0, 0, 0, 0)\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid rgba(0, 189, 119, 120);\n"
"    border-radius: 3px;\n"
"    height: 8px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:-1, x2:0.45, y2:0.16, stop:0 #8EC5FC, stop:1 #E0C3FC);\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"    border: 1px solid rgba(0, 170, 255, 150);\n"
"    width: 16px;\n"
"    margin: -5px 0;\n"
"    border-radius: 9px;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(17, 80, 260, 145))
        self.groupBox_2.setStyleSheet("background-color: rgba(255, 255, 255, 25);\n"
"border: 1px solid rgba(255, 255, 255, 35);\n"
"border-radius: 7px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(parent=self.groupBox_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(15, 60, 230, 20))
        font = QtGui.QFont()
        font.setFamily("Oswald,sans-serif")
        self.horizontalSlider_2.setFont(font)
        self.horizontalSlider_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ClosedHandCursor))
        self.horizontalSlider_2.setMouseTracking(False)
        self.horizontalSlider_2.setTabletTracking(False)
        self.horizontalSlider_2.setAcceptDrops(False)
        self.horizontalSlider_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.horizontalSlider_2.setAutoFillBackground(False)
        self.horizontalSlider_2.setStyleSheet("QSlider:horizontal {\n"
"    background-color: rgba(0, 0, 0, 0)\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid rgba(0, 189, 119, 120);\n"
"    border-radius: 3px;\n"
"    height: 8px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:-1, x2:0.45, y2:0.16, stop:0 #8EC5FC, stop:1 #E0C3FC);\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"    border: 1px solid rgba(0, 170, 255, 150);\n"
"    width: 16px;\n"
"    margin: -5px 0;\n"
"    border-radius: 9px;\n"
"}")
        self.horizontalSlider_2.setTracking(True)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setInvertedAppearance(False)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(176, 35, 61, 31))
        self.label_4.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(15, 90, 231, 41))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    padding-left: 10px;\n"
"    font-size: 14px;\n"
"    background-color: rgba(200, 200, 200, 200);\n"
"    border: 1px solid rgba(0, 170, 255, 30);\n"
"    border-radius: 5px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border: 1px solid rgba(0, 170, 255, 100);\n"
"    width: 15px;\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"}\n"
"QComboBox::drop-down:on{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/arr_dw.svg);\n"
"}\n"
"QComboBox::down-arrow:on {\n"
"    image: url(:/icons/arr_up.svg);\n"
"}\n"
"QAbstractItemView {\n"
"    border-radius: 0px;\n"
"    padding: 10px;\n"
"    background-color: rgb(200, 200, 200);\n"
"    border: 2px solid rgba(90, 160, 155, 200);\n"
"}\n"
"")
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 35, 141, 31))
        self.label_3.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(85, 10, 91, 31))
        self.label_2.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_2.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.comboBox.raise_()
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(325, 80, 261, 145))
        self.groupBox_3.setStyleSheet("background-color: rgba(255, 255, 255, 25);\n"
"border: 1px solid rgba(255, 255, 255, 35);\n"
"border-radius: 7px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(135, 83, 51, 51))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"}")
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_6)
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(60, 50, 141, 31))
        self.label_7.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(147, 15, 95, 25))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(0, 11, 161, 31))
        self.label_6.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(75, 83, 51, 51))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"}")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setChecked(False)
        self.pushButton_5.setAutoRepeat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.buttonGroup.addButton(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(195, 83, 51, 51))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"}")
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.buttonGroup.addButton(self.pushButton_7)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(15, 83, 51, 51))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"}\n"
"")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.buttonGroup.addButton(self.pushButton_4)
        self.pushButton_6.raise_()
        self.label_6.raise_()
        self.pushButton_5.raise_()
        self.pushButton_7.raise_()
        self.pushButton_4.raise_()
        self.label_7.raise_()
        self.pushButton.raise_()
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.horizontalSlider.raise_()
        self.rec_continue = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rec_continue.setGeometry(QtCore.QRect(375, 255, 51, 51))
        self.rec_continue.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rec_continue.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"")
        self.rec_continue.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/continue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rec_continue.setIcon(icon4)
        self.rec_continue.setIconSize(QtCore.QSize(50, 50))
        self.rec_continue.setObjectName("rec_continue")
        self.micro = QtWidgets.QLabel(parent=self.centralwidget)
        self.micro.setGeometry(QtCore.QRect(280, 140, 61, 61))
        self.micro.setMinimumSize(QtCore.QSize(51, 51))
        self.micro.setStyleSheet("background:rgba(0, 0, 0, 0) ;")
        self.micro.setText("")
        self.micro.setPixmap(QtGui.QPixmap(":/icons/micro.png"))
        self.micro.setScaledContents(True)
        self.micro.setObjectName("micro")
        self.rec_timer = QtWidgets.QLabel(parent=self.centralwidget)
        self.rec_timer.setGeometry(QtCore.QRect(106, 270, 81, 20))
        self.rec_timer.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.rec_timer.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.rec_timer.setObjectName("rec_timer")
        self.rec_timer.hide()
        self.minimize = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minimize.setGeometry(QtCore.QRect(540, 0, 40, 30))
        self.minimize.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.minimize.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(153, 153, 153, 180);\n"
"}")
        self.minimize.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimize.setIcon(icon5)
        self.minimize.setIconSize(QtCore.QSize(30, 30))
        self.minimize.setCheckable(True)
        self.minimize.setObjectName("minimize")
        self.close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.close.setGeometry(QtCore.QRect(580, 0, 40, 30))
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.close.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 0, 0, 200);\n"
"}")
        self.close.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/close.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close.setIcon(icon6)
        self.close.setIconSize(QtCore.QSize(21, 21))
        self.close.setCheckable(True)
        self.close.setObjectName("close")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 621, 30))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.icon = QtWidgets.QLabel(parent=self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(10, 4, 20, 20))
        self.icon.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/icons/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 0, 71, 25))
        self.label_9.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.groupBox.raise_()
        self.rec_start.raise_()
        self.rec_stop.raise_()
        self.rec_pause.raise_()
        self.rec_continue.raise_()
        self.micro.raise_()
        self.rec_timer.raise_()
        self.label_8.raise_()
        self.close.raise_()
        self.minimize.raise_()
        self.icon.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">1 Дн</span></p></body></html>"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Виділена пам\'ять:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">100%</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "122432"))
        self.comboBox.setItemText(1, _translate("MainWindow", "423675"))
        self.comboBox.setItemText(2, _translate("MainWindow", "23654"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Посилення мікрофону</span></p></body></html>"))
        self.label_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Мікрофон</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Мікрофон</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "1 год"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Розбивати файли по:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Вибрати"))
        self.label_6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Мікрофон</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Папка збереження:</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "30 хв"))
        self.pushButton_7.setText(_translate("MainWindow", "2 год"))
        self.pushButton_4.setText(_translate("MainWindow", "10 хв"))
        self.rec_timer.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">0:00:00</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Диктофон</span></p></body></html>"))
    def paintEvent(self, event):
        # Пользовательская отрисовка скругленных углов
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        
        # Рисуем скругленный прямоугольник
        rect = self.rect()
        radius = 20
        path = QPainterPath()
        path.addRoundedRect(QRectF(rect), radius, radius)
        
        # Рисуем пользовательский фон
        painter.setBrush(QColor(255, 255, 255))  # Цвет фона окна
        painter.setPen(Qt.PenStyle.NoPen)
        painter.drawPath(path)

        # Опционально: рисуем другой контент, если нужно
        painter.setCompositionMode(QPainter.CompositionMode.CompositionMode_DestinationOver)
        painter.setBrush(self.palette().window())
        painter.drawPath(path)