# Form implementation generated from reading ui file 'mini.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import resources
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MiniWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(139, 73)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.95, y2:0.16, stop:0 #8EC5FC, stop:1 #E0C3FC);\n"
"    font-family: \"Oswald\", sans-serif;\n"
"    border-radius: 7px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rec_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rec_start.setGeometry(QtCore.QRect(3, 3, 51, 51))
        self.rec_start.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rec_start.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"}\n"
"")
        self.rec_start.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/start.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rec_start.setIcon(icon)
        self.rec_start.setIconSize(QtCore.QSize(47, 47))
        self.rec_start.setCheckable(True)
        self.rec_start.setObjectName("rec_start")
        self.rec_pause = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rec_pause.setGeometry(QtCore.QRect(57, 3, 51, 51))
        self.rec_pause.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rec_pause.setAutoFillBackground(False)
        self.rec_pause.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 155), stop:0.301136 rgba(23, 140, 228, 155), stop:1 rgba(0, 189, 219, 155));\n"
"}\n"
"\n"
"\n"
"")
        self.rec_pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/pause.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rec_pause.setIcon(icon1)
        self.rec_pause.setIconSize(QtCore.QSize(43, 43))
        self.rec_pause.setObjectName("rec_pause")
        self.rec_timer_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.rec_timer_2.setGeometry(QtCore.QRect(3, 52, 51, 20))
        self.rec_timer_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.rec_timer_2.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.rec_timer_2.setObjectName("rec_timer_2")
        self.full_scr = QtWidgets.QPushButton(parent=self.centralwidget)
        self.full_scr.setGeometry(QtCore.QRect(110, 3, 26, 51))
        self.full_scr.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.full_scr.setAutoFillBackground(False)
        self.full_scr.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(37, 38, 41, 255), stop:0.340909 rgba(12, 13, 14, 255), stop:1 rgba(55, 66, 68, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.full_scr.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/full.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.full_scr.setIcon(icon2)
        self.full_scr.setIconSize(QtCore.QSize(20, 20))
        self.full_scr.setCheckable(True)
        self.full_scr.setChecked(False)
        self.full_scr.setObjectName("full_scr")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(112, 54, 21, 20))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SizeAllCursor))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/drag.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rec_timer_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">0:00:00</span></p></body></html>"))
