# Form implementation generated from reading ui file 'mini.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import resources
from PyQt6.QtGui import QIcon, QPixmap, QCursor
from PyQt6.QtCore import Qt, QSize, QRect, QCoreApplication, QMetaObject
from PyQt6.QtWidgets import QLabel, QPushButton, QWidget


class Ui_MiniWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(139, 73)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.95, y2:0.16, stop:0 #8EC5FC, stop:1 #E0C3FC);\n"
"    font-family: \"Oswald\", sans-serif;\n"
"    border-radius: 7px;\n"
"    color: black;\n"
"}")
        self.centralwidget = QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rec_start = QPushButton(parent=self.centralwidget)
        self.rec_start.setGeometry(QRect(3, 3, 51, 51))
        self.rec_start.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.rec_start.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.5, y2:0.5, stop:0.00568182 rgba(90, 160, 155, 200), stop:0.301136 rgba(23, 140, 128, 200), stop:1 rgba(0, 189, 119, 200));\n"
"}\n"
"")
        self.rec_start.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap(":/icons/start.png"), QIcon.Mode.Normal, QIcon.State.Off)
        self.rec_start.setIcon(icon)
        self.rec_start.setIconSize(QSize(47, 47))
        self.rec_start.setCheckable(True)
        self.rec_start.setObjectName("rec_start")
        self.rec_pause = QPushButton(parent=self.centralwidget)
        self.rec_pause.setGeometry(QRect(57, 3, 51, 51))
        self.rec_pause.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.rec_pause.setAutoFillBackground(False)
        self.rec_pause.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 255), stop:0.301136 rgba(23, 140, 228, 255), stop:1 rgba(0, 189, 219, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(90, 160, 255, 155), stop:0.301136 rgba(23, 140, 228, 155), stop:1 rgba(0, 189, 219, 155));\n"
"}\n"
"\n"
"\n"
"")
        self.rec_pause.setText("")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/icons/pause.png"), QIcon.Mode.Normal, QIcon.State.Off)
        self.rec_pause.setIcon(icon1)
        self.rec_pause.setIconSize(QSize(43, 43))
        self.rec_pause.setObjectName("rec_pause")
        self.rec_timer_2 =  QLabel(parent=self.centralwidget)
        self.rec_timer_2.setGeometry( QRect(3, 52, 51, 20))
        self.rec_timer_2.setLayoutDirection( Qt.LayoutDirection.LeftToRight)
        self.rec_timer_2.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.rec_timer_2.setObjectName("rec_timer_2")
        self.full_scr =  QPushButton(parent=self.centralwidget)
        self.full_scr.setGeometry( QRect(110, 3, 26, 51))
        self.full_scr.setCursor( QCursor( Qt.CursorShape.PointingHandCursor))
        self.full_scr.setAutoFillBackground(False)
        self.full_scr.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0.00568182 rgba(37, 38, 41, 255), stop:0.340909 rgba(12, 13, 14, 255), stop:1 rgba(55, 66, 68, 255));\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 12px;\n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.full_scr.setText("")
        icon2 =  QIcon()
        icon2.addPixmap( QPixmap(":/icons/full.png"),  QIcon.Mode.Normal,  QIcon.State.Off)
        self.full_scr.setIcon(icon2)
        self.full_scr.setIconSize( QSize(20, 20))
        self.full_scr.setCheckable(True)
        self.full_scr.setChecked(False)
        self.full_scr.setObjectName("full_scr")
        self.label =  QLabel(parent=self.centralwidget)
        self.label.setGeometry( QRect(112, 54, 21, 20))
        self.label.setCursor( QCursor( Qt.CursorShape.SizeAllCursor))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label.setText("")
        self.label.setPixmap( QPixmap(":/icons/drag.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate =  QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rec_timer_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">0:00:00</span></p></body></html>"))
